jupyterhub::jupyterhub_config_hash:
        SbatchForm:
                runtime:
                        min: 3.5
                        def: 3.5
                        max: 5.0
                nprocs:
                        min: 1
                        def: 1
                        max: 8
                memory:
                        min: 1024
                        max: 2048
                        def: 2048
                oversubscribe:
                        def: false
                        lock: false
                ui:
                        def: 'lab'

profile::freeipa::mokey::require_verify_admin: false
profile::software_stack::lmod_default_modules:  ['StdEnv/2023', 'fsl/6.0.7.7', 'octave/7.2.0']
