jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 3.5
      def: 3.5
      max: 8.0
    nprocs:
      min: 1
      def: 1
      max: 8
    memory:
      min: 1024
      max: 60000
      def: 2048
    oversubscribe:
      def: true
      lock: false
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: false

profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc'
  - 'mii'
  - 'openmpi'
  - 'symengine/0.11.2'
  - 'cuda/12.9'
  - 'cuquantum/25.06.0.10'

jupyterhub::kernel::venv::packages:
  - 'numpy'
  - 'scikit-learn'
  - 'pandas'
  - 'torch<2.12'
  - 'torchvision'
  - 'scipy'
  - 'scikit-image'
  - 'networkx'
  - 'matplotlib'
  - 'pennylane==0.45'
  - 'pennylane-calculquebec'
  - 'pennylane-lightning==0.45'
  - 'pennylane-lightning-gpu==0.45'
  - 'qiskit'
  - 'qiskit-calculquebec'
  - 'qiskit-ibm-runtime'
  - 'merlinquantum'
  - 'perceval_quandela'
  - 'mitiq'

profile::accounts::skel_archives:
  - filename: ciq101-main.zip
    source: https://github.com/calculquebec/ciq101/archive/refs/heads/main.zip
  - filename: ciq102-main.zip
    source: https://github.com/calculquebec/ciq102/archive/refs/heads/main.zip
  - filename: mnq101-main.zip
    source: https://github.com/calculquebec/mnq101/archive/refs/heads/main.zip
