jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 3.5
      def: 3.5
      max: 8.0
    nprocs:
      min: 1
      def: 1
      max: 8
    memory:
      min: 1024
      max: 60000
      def: 2048
    oversubscribe:
      def: true
      lock: false
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: false

profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc'
  - 'mii'
  - 'python/3.12'
  - 'openmpi'

jupyterhub::kernel::venv::packages:
  - 'numpy'
  - 'scikit-learn'
  - 'pandas'
  - 'torch'
  - 'torchvision'
  - 'scipy'
  - 'scikit-image'
  - 'scikit-learn'
  - 'networkx'
  - 'matplotlib'
  - 'pennylane'
  - 'pennylane-calculquebec'
  - 'qiskit'
  - 'qiskit_algorithms'
  - 'qiskit_aer'
  - 'qiskit_ibm_runtime'
  - 'qiskit_machine_learning'
  - 'qiskit_nature'
  - 'qiskit_optimization'
  - 'pennylane-lightning-gpu'

profile::freeipa::mokey::enable_user_signup: true
profile::freeipa::mokey::require_verify_admin: true

jupyterhub::kernel::venv::python: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.12.4/bin/python3
jupyterhub::kernel::venv::prefix: /opt/ipython-kernel-3.12

profile::accounts::skel_archives:
  - filename: programme-ete-quantique-main.zip
    source: https://github.com/calculquebec/programme-ete-quantique/archive/refs/heads/main.zip
  - filename: cache.zip
    source: https://github.com/calculquebec/.cache/releases/download/v1/cache-v1.zip
  - filename: jupyter.zip
    source: https://github.com/calculquebec/jupyterlab-settings/releases/download/v1.0.1/jupyter-v1.0.1.zip
