locals {
  default_pod = {
    nnodes = {
      gpu = 0
      gpupool = 9
    }
    home_size = 300
    project_size = 1500
    scratch_size = 100

    user_quotas = {
      home = "3g"
      project = "6g"
      scratch = "2g"
    }
    mig = {
      gpu = { "2g.10gb" = 4 }
    }
  }
  name = "ift6759"
}
