profile::software_stack::lmod_default_modules:
  - 'gcc'
  - 'minimap2'
  - 'samtools'
  - 'fastqc'
  - 'bedtools'
  - 'bwa'
  - 'seqkit'
  - 'trimmomatic'
  - 'subread'
  - 'augustus'
  - 'hmmer'
  - 'metaeuk'
  - 'prodigal'
  - 'r/4.3.1'
  - 'bbmap'
  - 'r-bundle-bioconductor/3.18'
  - 'blast+/2.14.1'
  - 'arrow'
  - 'python/3.11'
  - 'percolator'

jupyterhub::kernel::venv::packages: ['flye', 'msgpack', 'deeptools', 'quast', 'biopython', 'pandas', 'busco', 'hicexplorer', 'pygenometracks', 'pyteomics', 'macs3', 'mokapot', 'numpy<2']
