jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 3.5
      def: 3.5
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 1
    memory:
      min: 1024
      max: 2048
      def: 2048
    oversubscribe:
      def: true
      lock: true
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: false

profile::freeipa::mokey::require_verify_admin: true
profile::users::ldap::users:
  mdion:
    count: 1
    groups: ['def-prof1', 'def-prof2']
    passwd: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQAwDQYJKoZIhvcNAQEBBQAEggEAQilvoeDDg/DryQAyBd8Oc0/brIiJrmxfE2jFXNV8jN7d1yeWKdSevfsE+2JmDEBmAkC8l1j5t+fCIHCse0lnSpgUiiF0PJJ54QoMD4vDMKbq4y8USsLgOOT1aLexkRTPr7BM3batpoG/IrBqT7ZgDugJ2siYCiwIQ1XesG4pGT3liGqllIqhmopHFZPddrkprvsThhLz/edQJvHIljl2xzOoyXvNuRsS08zILpPR7SvVWaPq95aw4ceh1/D14K2dDHtrSLTkaJciOpsVBlBehCXTLmDFMdGQnqlXnYlAidb8sqc3WpvGFg4Dh0rwakMMYdQRE+qtx4YAs8gT6YlDAjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBCHUnnOEi03JQOpAIhiMwi3gBAXRVqMNicC+SdHqDXNqMgq]
  etudiant:
    count: 1
    groups: ['def-prof1', 'def-prof2']
  collab3:
    count: 1
    groups: ['def-prof1', 'def-prof2']
  postdoc4:
    count: 1
    groups: ['def-prof1', 'def-prof2']


profile::slurm::accounting::accounts:
  def-prof1:
    Fairshare: 1
    MaxJobs: 10
  def-prof2:
    Fairshare: 1
    MaxJobs: 10
