jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    memory:
      min: 1024
      max: 10000
      def: 2048
    ui:
      def: 'lab'

  SlurmFormSpawner:
    disable_form: false

# jupyterhub::kernel::venv::packages: ['numpy']

profile::software_stack::extra_site_env_vars:
  R_LIBS: '/project/def-sponsor00/R/4.4.0'
  OMPI_MCA_btl_base_exclude: 'smcuda'

profile::freeipa::mokey::enable_user_signup: true
profile::software_stack::lmod_default_modules:
  - 'cuda/12.6'

profile::accounts::skel_archives:
  - filename: cache.zip
    source: https://github.com/calculquebec/.cache/releases/download/v1/cache-v1.zip
  - filename: jupyter.zip
    source: https://github.com/calculquebec/jupyterlab-settings/releases/download/v1/jupyter-v1.zip
