jupyterhub::slurmformspawner::version: 2.5.1
profile::software_stack::lmod_default_modules: ['StdEnv/2020', 'gcc/9.3.0', 'openmpi/4.0.3', 'cuda/11.4', 'python/3.10', 'ipython-kernel/3.10', 'opencv/4.8.0', 'arrow/13.0.0', "ijulia-kernel/1.8", "openrefine/3.4.1"]

jupyterhub::jupyterhub_config_hash:
      SlurmFormSpawner:
        start_timeout: 900
        http_timeout: 300

profile::slurm::base::suspend_time: 7200
profile::slurm::base::resume_timeout: 7200
