jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 3.5
      def: 3.5
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 1
    memory:
      min: 1024
      max: 2048
      def: 2048
    oversubscribe:
      def: true
      lock: true
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: false

jupyterhub::kernel::venv::packages: ['numpy']

profile::freeipa::mokey::enable_user_signup: true
profile::freeipa::mokey::require_verify_admin: false

profile::accounts::skel_archives:
    - filename: cache.zip
      source: https://github.com/calculquebec/.cache/releases/download/v1/cache-v1.zip
    - filename: jupyter.zip
      source: https://github.com/calculquebec/jupyterlab-settings/releases/download/v1/jupyter-v1.zip

cron::job:
  spawn_nodes:
    command: '#/opt/software/slurm/bin/scontrol update node=nodecpupool[1-5] state=power_up'
    minute: '*/30'
    hour: '*'
    date: '*'
    month: '*'
    weekday: '4'
    user: 'root'
    description: 'spawn nodes every 30 minutes on thursday'
    environment: ['CRON_TZ=America/New_York']
