jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 3.5
      def: 3.5
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 1
    memory:
      min: 1024
      max: 2048
      def: 2048
    oversubscribe:
      def: true
      lock: true
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: false

profile::users::ldap::users:
  dummy_cours1:
    count: 1
    groups: ['def-cours1']

  dummy_cours2:
    count: 1
    groups: ['def-cours2']

  dummy_cours3:
    count: 1
    groups: ['def-cours3']

profile::slurm::accounting::accounts:
  def-cours1:
    Fairshare: 1
    MaxJobs: 1
  def-cours2:
    Fairshare: 1
    MaxJobs: 10
  def-cours3:
    Fairshare: 1
    MaxJobs: 10

cron::job:
  spawn_nodes:
    command: '#/opt/software/slurm/bin/scontrol update node=nodegpupool[1-5] state=power_up'
    minute: '*/30'
    hour: '*'
    date: '*'
    month: '*'
    weekday: '4'
    user: 'root'
    description: 'spawn nodes every 30 minutes on thursday'
    environment: ['CRON_TZ=America/New_York']

profile::users::ldap::users:
  'maxime':
    count: 1
    passwd: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQAwDQYJKoZIhvcNAQEBBQAEggEAmEHAlOApxZn0m4YGLGZblPwfSkN6Uo0RdZhKzrd1b4mVG3xIot95Gucud7lE1rC4Xt8ceKdLu11YRW7TnYpXQYOUhC/A4/Qz/GHk6sA3JMXCoFgVBRSq/opFvYzBPvl933jXXesZvLKABT5/0gv0px5d4Cl45OHZcFCMOCE+JqDIsCGoxHGBdCIa/hBaGCw29Qz3NRjzCxQ1wrSOw5wkb0tpaKhhSOjopE4gYMA7qVKRdk4nVYX5h3n0/H1IOQGCCgLBnhGI15mrDi/b8OcZ+b14sqZ6OzrRMR0s/wscx81nMwyE+P2u1oe87ii45kauksyYE3XgIkN16gwe0BA2FTBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAK9GXFh6uOsBo+K5Osw0Q0gCBFOXuOSRTz6oyOEExlsqe0VS6p9BMLkPNa/PvSzUZPYw==]
    groups: ['def-sponsor00', 'admins']

