
profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020', 'gcc/9.3.0', 'openmpi/4.0.3', 'python/3.9', 'ipython-kernel/3.9']

jupyterhub::jupyterhub_config_hash:
    SlurmFormSpawner:
        disable_form: true

lookup_options:
    jupyterhub::kernel::venv::pip_environment:
        merge: deep
jupyterhub::kernel::venv::pip_environment:
    PIP_NO_INDEX: 1
jupyterhub::kernel::venv::packages: ['PennyLane']

profile::users::ldap::users:
    usr:
        count: 50
        passwd: "%{alias('passwd_user')}"
        groups: ['def-sponsor00']
    
    instructor:
        passwd: "%{alias('passwd_instructor')}"
        groups: ['def-sponsor00', 'helper']

    helper:
        count: 4
        passwd: "%{alias('passwd_helper')}"
        groups: ['def-sponsor00', 'helper']
