jupyterhub::jupyterhub_config_hash:
        SbatchForm:
                runtime:
                        min: 3.5
                        def: 3.5
                        max: 5.0
                nprocs:
                        min: 1
                        def: 1
                        max: 8
                memory:
                        min: 1024
                        max: 30000
                        def: 2048
                oversubscribe:
                        def: true
                        lock: false
                ui:
                        def: 'lab'
        SlurmFormSpawner:
                disable_form: false

jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib', 'seaborn']

cron::job:
        spawn_nodes:
                command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-17] state=power_up'
                minute: '20'
                hour: '08'
                month: '1-4'
                weekday: '3'
                user: 'root'
                description: 'spawn nodes at 08:20 on each Wednesday'
                environment: ['CRON_TZ=America/New_York']
