jupyterhub::slurmformspawner::version: 2.5.1
profile::software_stack::lmod_default_modules: ['StdEnv/2023', 'nvhpc/23.9', 'openmpi/4.1.5', 'cuda/12.2', 'java/1.8']
profile::slurm::base::enable_tmpfs_mounts: true

jupyterhub::jupyterhub_config_hash:
      SlurmFormSpawner:
        start_timeout: 900
        http_timeout: 300

profile::slurm::base::suspend_time: 7200
profile::slurm::base::resume_timeout: 7200
