jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    memory:
      min: 1024
      max: 4096
      def: 2048
    gpus:
      def: 'gpu:0'
      choices: ['gpu:0', 'gpu:1']

jupyterhub::kernel::venv::packages: ['tensorflow==2.19.1', 'torch<2.12', 'simpleITK', 'monai', 'tensorboard', 'tqdm', 'nibabel', 'numpy', 'matplotlib', 'holoviews', 'torchinfo', 'torchvision', 'umap-learn', 'h5py']
