jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 3.5
      def: 3.5
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 8
    memory:
      min: 1024
      max: 30000
      def: 2048
    oversubscribe:
      def: true
      lock: false
    gpus:
      def: 'gpu:1g.5gb:1,shard:1'
      choices: ['gpu:0', 'gpu:1g.5gb:1', 'gpu:1g.5gb:1,shard:1']
    ui:
      def: 'lab'
    partition:
      lock: false
  SlurmFormSpawner:
    disable_form: false

profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc'
  - 'mii'
  - 'python/3.11'

jupyterhub::kernel::venv::packages:
  - 'numpy<2'
  - 'torch==2.5.1'
  - 'torchvision'
  - 'pandas'
  - 'matplotlib'
  - 'scikit-learn'
  - 'graphviz'
  - 'gensim'
  - 'scipy'
  - 'Pillow'
  - 'poutyne'
  - 'einops'
  - 'transformers[torch]'

jupyterhub::kernel::venv::pip_environment:
  PYTHONPATH: /cvmfs/soft.computecanada.ca/easybuild/python/site-packages:/cvmfs/soft.computecanada.ca/custom/python/site-packages
jupyterhub::kernel::venv::kernel_environment:
  PYTHONPATH: "/cvmfs/soft.computecanada.ca/easybuild/python/site-packages:${PYTHONPATH}"
  EBPYTHONPREFIXES: "${SLURM_TMPDIR}:${EBPYTHONPREFIXES}"

cron::job:
  spawn_nodes_jan:
    command: '/opt/software/slurm/bin/scontrol update node=nodegpupool[1-9] state=power_up'
    minute: '25'
    hour: '8'
    date: '17,24,31'
    month: '1'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on January Fridays'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_feb:
    command: '/opt/software/slurm/bin/scontrol update node=nodegpupool[1-9] state=power_up'
    minute: '25'
    hour: '8'
    date: '7,14,21,28'
    month: '2'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on February Fridays'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_mar:
    command: '/opt/software/slurm/bin/scontrol update node=nodegpupool[1-9] state=power_up'
    minute: '25'
    hour: '8'
    date: '14,21,28'
    month: '3'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on March Fridays'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_apr:
    command: '/opt/software/slurm/bin/scontrol update node=nodegpupool[1-9] state=power_up'
    minute: '25'
    hour: '8'
    date: '4,11,18,25'
    month: '4'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on April Fridays'
    environment: ['CRON_TZ=America/New_York']
