jupyterhub::jupyterhub_config_hash:
        SbatchForm:
                runtime:
                        min: 3.5
                        def: 3.5
                        max: 5.0
                nprocs:
                        min: 1
                        def: 1
                        max: 8
                memory:
                        min: 1024
                        max: 30000
                        def: 2048
                oversubscribe:
                        def: true
                        lock: false
                gpus: 
                        def: 'gpu:0'
                        choices: ['gpu:0', 'gpu:3g.20gb:1', 'gpu:3g.20gb:1,shard:1']
                ui:
                        def: 'lab'
                partition:
                        lock: false
        SlurmFormSpawner:
                disable_form: false

profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc'
  - 'mii'
  - 'python/3.11'

jupyterhub::kernel::venv::packages:
  - 'torch==2.5.1'
  - 'torchvision'
  - 'pandas'
  - 'matplotlib'
  - 'scikit-learn'
  - 'graphviz'
  - 'gensim'
  - 'numpy<2'
  - 'scipy'
  - 'Pillow'
  - 'poutyne'
  - 'einops'
  - 'transformers[torch]'

jupyterhub::kernel::venv::pip_environment:
  PYTHONPATH: /cvmfs/soft.computecanada.ca/easybuild/python/site-packages:/cvmfs/soft.computecanada.ca/custom/python/site-packages
  EBPYTHONPREFIXES: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/scipy-stack/2024a:/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/ipykernel/2024a:/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcc12/opencv/4.10.0
jupyterhub::kernel::venv::kernel_environment:
  PYTHONPATH: "/cvmfs/soft.computecanada.ca/easybuild/python/site-packages:${PYTHONPATH}"
  EBPYTHONPREFIXES: "${SLURM_TMPDIR}:${EBPYTHONPREFIXES}"
