jupyterhub::jupyterhub_config_hash:
        SbatchForm:
                runtime:
                        min: 3.5
                        def: 3.5
                        max: 5.0
                nprocs:
                        min: 1
                        def: 1
                        max: 1
                memory:
                        min: 1024
                        max: 2048
                        def: 2048
                oversubscribe:
                        def: true
                        lock: true
                ui:
                        def: 'terminal'
        SlurmFormSpawner:
                disable_form: true

profile::freeipa::mokey::require_verify_admin: false
profile::cvmfs::client::lmod_default_modules: ['StdEnv/2023', 'gcc/12.3.0', 'openmpi/4.1.5', 'python/3.10', 'ipython-kernel/3.10']
