profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc'
  - 'mii'
  - 'python/3.11'

jupyterhub::kernel::venv::pip_environment:
  PYTHONPATH: /cvmfs/soft.computecanada.ca/easybuild/python/site-packages:/cvmfs/soft.computecanada.ca/custom/python/site-packages
jupyterhub::kernel::venv::kernel_environment:
  PYTHONPATH: "/cvmfs/soft.computecanada.ca/easybuild/python/site-packages:${PYTHONPATH}"
  EBPYTHONPREFIXES: "${SLURM_TMPDIR}:${EBPYTHONPREFIXES}"

cron::job:
  spawn_nodes:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-2] state=power_up'
    minute: '25'
    hour: '10'
    month: '1-4'
    weekday: '4'
    user: 'root'
    description: 'spawn nodes at 10:25 on each Thursdays'
  spawn_nodes_jan:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-2] state=power_up'
    minute: '25'
    hour: '8'
    date: '29'
    month: '1'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on 29 January'
  spawn_nodes_feb:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-2] state=power_up'
    minute: '25'
    hour: '8'
    date: '12'
    month: '2'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on 12 February'
  spawn_nodes_apr:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-2] state=power_up'
    minute: '25'
    hour: '8'
    date: '2,16'
    month: '4'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on for April'
