jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      def: 2.0
    memory:
      min: 1024
      max: 1000
      def: 8192
    oversubscribe:
      def: true
      lock: true
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: false

#jupyterhub::kernel::venv::packages: ['numpy']

profile::freeipa::mokey::enable_user_signup: true

profile::accounts::skel_archives:
  - filename: cache.zip
    source: https://github.com/calculquebec/.cache/releases/download/v1/cache-v1.zip
  - filename: jupyter.zip
    source: https://github.com/calculquebec/jupyterlab-settings/releases/download/v1/jupyter-v1.zip

cron::job:
  spawn_nodes:
    command: '/opt/software/slurm/bin/scontrol update node=ALL state=power_up'
    minute: '25'
    hour: '10'
    month: '1-4'
    weekday: '4'
    user: 'root'
    description: 'spawn nodes at 10:25 on each Thursdays'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_jan:
    command: '/opt/software/slurm/bin/scontrol update node=ALL state=power_up'
    minute: '25'
    hour: '9'
    date: '28'
    month: '1'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 9:25 on 28 January'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_feb:
    command: '/opt/software/slurm/bin/scontrol update node=ALL state=power_up'
    minute: '25'
    hour: '9'
    date: '11'
    month: '2'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 9:25 on 11 February'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_apr:
    command: '/opt/software/slurm/bin/scontrol update node=ALL state=power_up'
    minute: '25'
    hour: '9'
    date: '1,15'
    month: '4'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 9:25 on for April'
    environment: ['CRON_TZ=America/New_York']
