jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 1.0
      def: 2.0
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 8
    memory:
      min: 1024
      max: 10000
      def: 6144
    oversubscribe:
      def: true
      lock: true
    ui:
      def: 'lab'
    partition:
      lock: false
  SlurmFormSpawner:
    disable_form: false

profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc'
  - 'mii'

cron::job:
  spawn_nodes:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-2] state=power_up'
    minute: '25'
    hour: '10'
    month: '1-4'
    weekday: '4'
    user: 'root'
    description: 'spawn nodes at 10:25 on each Thursdays'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_jan:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-2] state=power_up'
    minute: '25'
    hour: '8'
    date: '29'
    month: '1'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on 29 January'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_feb:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-2] state=power_up'
    minute: '25'
    hour: '8'
    date: '12'
    month: '2'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on 12 February'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_apr:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-2] state=power_up'
    minute: '25'
    hour: '8'
    date: '2,16'
    month: '4'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on for April'
    environment: ['CRON_TZ=America/New_York']
