jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 3.5
      def: 3.5
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 1
    memory:
      min: 1024
      max: 2048
      def: 2048
    oversubscribe:
      def: true
      lock: true
    gpus:
      def: 'gpu:0'
      choices: ['gpu:0', 'gpu:1g.5gb:1', 'gpu:3g.20gb:1' ]
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: false

profile::software_stack::lmod_default_modules: ['StdEnv/2023', 'gcc/12.3', 'openmpi/4.1.5', 'python/3.10', 'ipython-kernel/3.10']
profile::freeipa::mokey::require_verify_admin: true
profile::slurm::base::slurm_version: '24.05'

