profile::users::ldap::users:
  user:
    count: 200
    passwd: "%{alias('passwd_user')}"
    groups: ['def-sponsor00']

  instructor:
    count: 3
    passwd: "%{alias('passwd_instructor')}"
    groups: ['def-sponsor00', 'helper']

  helper:
    count: 9
    passwd: "%{alias('passwd_helper')}"
    groups: ['def-sponsor00', 'helper']

  'mboisson':
    count: 1
    passwd: ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQAwDQYJKoZIhvcNAQEBBQAEggEAmEHAlOApxZn0m4YGLGZblPwfSkN6Uo0RdZhKzrd1b4mVG3xIot95Gucud7lE1rC4Xt8ceKdLu11YRW7TnYpXQYOUhC/A4/Qz/GHk6sA3JMXCoFgVBRSq/opFvYzBPvl933jXXesZvLKABT5/0gv0px5d4Cl45OHZcFCMOCE+JqDIsCGoxHGBdCIa/hBaGCw29Qz3NRjzCxQ1wrSOw5wkb0tpaKhhSOjopE4gYMA7qVKRdk4nVYX5h3n0/H1IOQGCCgLBnhGI15mrDi/b8OcZ+b14sqZ6OzrRMR0s/wscx81nMwyE+P2u1oe87ii45kauksyYE3XgIkN16gwe0BA2FTBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAK9GXFh6uOsBo+K5Osw0Q0gCBFOXuOSRTz6oyOEExlsqe0VS6p9BMLkPNa/PvSzUZPYw==]
    groups: ['def-sponsor00', 'admins']
  'helene':
    count: 1
    passwd: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQAwDQYJKoZIhvcNAQEBBQAEggEAJ6nf+JXAomiYQlz5cZdjiooFxkzVL3zIK6d3dKBAXV4WEFGyg8Vh6XzKTCHW0/BUhxn8SsMrfiEqjG/GX7gG+JRByOwZJPAE6UWxI9iNa2yPy9ug7Bry1I7Cl3iuSNx9NENF+Rhk0JM4ZSzALAwIYGR/LSA4NDvMIwgX0N/+EZzYB+OZLxTgRokJ4yxe8kXzQuwD4wkmr4+uw0riB/MlpCg1fxf1dsvn5uTVDE3d9Ic1EZoFSpuNBGNB5Bix9tqbqge+gbhSg2v79aewOZKs0AI0bMp9wmQn2OGEaF+SNYki/9VN3ZCk+oiXzLy+I5CjeRUEO0GWDm4gH6vukkO5czA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBClbtm4aGLsLWI+adu8q0PKgBCWFEK/OG8afUdF/ff9fQY7]
    groups: ['def-sponsor00', 'admins']

profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc/12.3'
  - 'cuda/12.2'
  - 'chapel-ucx-cuda/2.4.0'

jupyterhub::kernel::venv::packages:
  - 'numba'
  - 'numba_cuda'
  - 'cupy'
  - 'polars'
  - 'numpy'
  - 'jax'
  - 'jax[cuda]'
  - 'pillow'
  - 'flax'
