jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 3.5
      def: 3.5
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 8
    memory:
      min: 1024
      max: 29000
      def: 2048
    oversubscribe:
      def: true
      lock: false
    ui:
      def: 'lab'
  SlurmFormSpawner:
    disable_form: false

# jupyterhub::kernel::venv::packages: ['numpy']

profile::freeipa::mokey::enable_user_signup: true

profile::accounts::skel_archives:
  - filename: cache.zip
    source: https://github.com/calculquebec/.cache/releases/download/v1/cache-v1.zip
  - filename: jupyter.zip
    source: https://github.com/calculquebec/jupyterlab-settings/releases/download/v1/jupyter-v1.zip

cron::job:
  spawn_nodes_jan:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-5] state=power_up'
    minute: '25'
    hour: '12'
    date: '7,14,21,28'
    month: '1'
    user: 'root'
    description: 'spawn a few nodes on Wednesdays in January, at 12:25'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_feb:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-5] state=power_up'
    minute: '25'
    hour: '12'
    date: '4,11,18,25'
    month: '2'
    user: 'root'
    description: 'spawn a few nodes on Wednesdays in February, at 12:25'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_mar:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-5] state=power_up'
    minute: '25'
    hour: '12'
    date: '11,18,25'
    month: '3'
    user: 'root'
    description: 'spawn a few nodes on Wednesdays in March, at 12:25'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_apr:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-5] state=power_up'
    minute: '25'
    hour: '12'
    date: '8,15'
    month: '4'
    user: 'root'
    description: 'spawn a few nodes on Wednesdays in April, at 12:25'
    environment: ['CRON_TZ=America/New_York']
