jupyterhub::enable_otp_auth: false

jupyterhub::jupyterhub_config_hash:
  SlurmFormSpawner:
    start_timeout: 900

profile::freeipa::mokey::require_verify_admin: false
profile::slurm::base::slurm_version: '23.02'
