jupyterhub::enable_otp_auth: false

jupyterhub::jupyterhub_config_hash:
  SlurmFormSpawner:
    start_timeout: 900

    
profile::cvmfs::client::lmod_default_modules: ['StdEnv/2020', 'gcc/9.3.0', 'openmpi/4.0.3', 'cuda/11.7', 'python/3.10', 'ipython-kernel/3.10']

profile::freeipa::mokey::require_verify_admin: false
profile::slurm::base::slurm_version: '23.02'
