jupyterhub::enable_otp_auth: false

jupyterhub::jupyterhub_config_hash:
  SlurmFormSpawner:
    start_timeout: 900

profile::freeipa::mokey::require_verify_admin: true
profile::slurm::base::slurm_version: '23.02'
# when using snapshots, it is quick enough to boot nodes that 900 seconds is enough for suspend
profile::slurm::base::suspend_time: 900
profile::gpu::install::passthrough::nvidia_driver_stream: '550-dkms'

prometheus::global_config:
  scrape_interval: '1m'
  scrape_timeout: '1m'
  external_labels:
    cluster: "%{alias('cluster_name')}"
    cloud: "%{alias('cloud_name')}"
    team: 'calculquebec'
    purpose: "%{alias('cluster_purpose')}"
    replica: '1'

prometheus::remote_write_configs:
  - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
    basic_auth:
      username: 'cqformation'
      password: "%{alias('prometheus_password')}"

profile::software_stack::lmod_default_modules: ['StdEnv/2023']
jupyterhub::kernel::venv::python: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/bin/python3
jupyterhub::kernel::venv::prefix: /opt/ipython-kernel-3.11
lookup_options:
  jupyterhub::kernel::venv::pip_environment:
    merge: deep
jupyterhub::kernel::venv::pip_environment:
  PIP_NO_INDEX: 1
  PIP_CONFIG_FILE: /cvmfs/soft.computecanada.ca/config/python/pip-x86-64-v3-gentoo2023.conf

magic_castle::site::tags:
  cron:
    - cron
