jupyterhub::jupyterhub_config_hash:
        SbatchForm:
                runtime:
                        min: 3.5
                        def: 3.5
                        max: 5.0
                nprocs:
                        min: 1
                        def: 1
                        max: 8
                memory:
                        min: 1024
                        max: 2048
                        def: 2048
                oversubscribe:
                        def: false
                        lock: false
                ui:
                        def: 'lab'

profile::freeipa::mokey::require_verify_admin: true
profile::software_stack::lmod_default_modules: ['StdEnv/2020', 'gcc/9.3.0', "ipython-kernel/3.10"]
