jupyterhub::enable_otp_auth: false

jupyterhub::jupyterhub_config_hash:
  SlurmFormSpawner:
    start_timeout: 900

profile::freeipa::mokey::require_verify_admin: true
profile::slurm::base::slurm_version: '23.02'
# when using snapshots, it is quick enough to boot nodes that 900 seconds is enough for suspend
profile::slurm::base::suspend_time: 900
profile::gpu::install::passthrough::nvidia_driver_stream: '550-dkms'

prometheus::global_config:
  scrape_interval: '1m'
  scrape_timeout: '1m'
  external_labels:
    cluster: "%{alias('cluster_name')}"
    cloud: "%{alias('cloud_name')}"
    team: 'calculquebec'
    purpose: "%{alias('cluster_purpose')}"
    replica: '1'

prometheus::remote_write_configs:
  - url: 'https://thanos-receive.dant.computecanada.ca/api/v1/receive'
    basic_auth:
      username: 'cqformation'
      password: "%{alias('prometheus_password')}"
