jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 1.0
      def: 5.0
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 4
    memory:
      min: 1024
      max: 15000
      def: 4096
    oversubscribe:
      def: true
      lock: false
    ui:
      def: 'lab'
    partition:
      lock: false
  SlurmFormSpawner:
    disable_form: false

profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc'
  - 'mii'

cron::job:
  spawn_nodes_feb:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool[1-10] state=power_up'
    minute: '55'
    hour: '9'
    date: '20,21'
    month: '2'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes'
    environment: ['CRON_TZ=America/New_York']
