jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 1.0
      def: 5.0
      max: 5.0
    nprocs:
      min: 1
      def: 1
      max: 1
    memory:
      min: 1024
      max: 15000
      def: 2048
    oversubscribe:
      def: true
      lock: true
    ui:
      def: 'lab'
    partition:
      lock: false
  SlurmFormSpawner:
    disable_form: false

profile::software_stack::lmod_default_modules:
  - 'StdEnv/2023'
  - 'gcc'
  - 'mii'

jupyterhub::kernel::venv::packages: ['numpy', 'pandas', 'matplotlib', 'biopython']

profile::accounts::skel_archives:
  - filename: jupyter.zip
    source: https://drive.google.com/uc?export=download&id=1hFNla811miJFnfSGg7Lw3GZhb7VPDYZB

  - filename: matplotlib.zip
    source: https://drive.google.com/uc?export=download&id=1vwrd7xNAy9WwFQLbSbZuBPQ0YtupiNnH

cron::job:
  spawn_nodes_feb:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool1 state=power_up'
    minute: '25'
    hour: '8'
    date: '24'
    month: '2'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on 24 February'
    environment: ['CRON_TZ=America/New_York']
  spawn_nodes_mar:
    command: '/opt/software/slurm/bin/scontrol update node=nodecpupool1 state=power_up'
    minute: '25'
    hour: '8'
    date: '10,24'
    month: '3'
    weekday: '*'
    user: 'root'
    description: 'spawn nodes at 8:25 on for March'
    environment: ['CRON_TZ=America/New_York']
