profile::cvmfs::client::lmod_default_modules: ['StdEnv/2023', 'rstudio-server/4.3']
profile::accounts::skel_archives:
  - filename: src.tar.gz
    source: https://github.com/calculquebec/mc-infra-cours/raw/main/sc-seq-ws/src.tar.gz
  - filename: rlibs-0.tar.gz
    source: https://github.com/calculquebec/mc-infra-cours/raw/main/sc-seq-ws/rlibs-0.tar.gz
  - filename: rlibs-1.tar.gz
    source: https://github.com/calculquebec/mc-infra-cours/raw/main/sc-seq-ws/rlibs-1.tar.gz
  - filename: rlibs-2.tar.gz
    source: https://github.com/calculquebec/mc-infra-cours/raw/main/sc-seq-ws/rlibs-2.tar.gz
  - filename: rlibs-3.tar.gz
    source: https://github.com/calculquebec/mc-infra-cours/raw/main/sc-seq-ws/rlibs-3.tar.gz
  - filename: rlibs-4.tar.gz
    source: https://github.com/calculquebec/mc-infra-cours/raw/main/sc-seq-ws/rlibs-4.tar.gz
  - filename: rlibs-5.tar.gz
    source: https://github.com/calculquebec/mc-infra-cours/raw/main/sc-seq-ws/rlibs-5.tar.gz
