name: Linting

# yamllint disable-line rule:truthy
on:
  push:
    branches: [ "2024-3" ]
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches: [ "2024-3" ]
    paths:
      - '**.yaml'
      - '**.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint --format github .
